server:
  port: 80
  session:
    timeout: 600
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://xxxxxxxxx:xx/test?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true&amp;autoReconnect=true;useSSL=false
    #password:
    #username:
  redis:
    host: 47.98.158.193
    port: 6378
    password: evan
  session:
    store-type: redis

zeus:
  social:
    filterProcessesUrl: /auth
    signUpUrl: /demo-signUp.html
    #qq:
      #app-id:
      #app-secret:
      #providerId: qq.do
    #weixin:
      #app-id:
      #app-secret:
  security:
    browser:
      #loginPage: /demo-signIn.html
      #loginType: REDIRECT
      signOutUrl: /demo-signOut.html
      signUpUrl: /demo-signUp.html
    code:
      image:
        length: 6
        width: 100
        height: 33
        url: /oauth/token
    oauth2Propertites:
      oauth2ClientProperties[0]:
        clientId: zeusClientId
        clentSecurity: zeusSecret


